//! The catalogue of validation gates: V-number → property → analytical reference → the
//! test that checks it.
//!
//! This is the machine-readable twin of the validation tables in `docs/design/`. It
//! exists so `validation_report` can print what was checked and against what, rather than
//! a bare list of green test names — a gate is only meaningful alongside the closed form
//! it is compared to.
//!
//! It cannot silently drift: `tests/catalogue.rs` asserts that every gate here names a
//! test that exists, and that every `vNN_*` test in the suite appears here.

/// One validation gate, as stated in its `docs/design/` section.
pub struct Gate {
    /// Gate number, e.g. `"V14"`.
    pub id: &'static str,
    /// The property being constrained.
    pub property: &'static str,
    /// The closed form or documented invariant it is checked against — the part that
    /// makes it validation rather than a regression test.
    pub reference: &'static str,
    /// The test function(s) that enforce it.
    pub tests: &'static [&'static str],
}

/// Every gate, in number order. `docs/design/` is the prose source of truth (and
/// `docs/VALIDATION.md` the reader's table); this is
/// the executable index into it.
pub const GATES: &[Gate] = &[
    Gate { id: "V1", property: "world<->cell round-trip", reference: "world_to_cell(cell_center(c)) == c for all cells", tests: &["world_cell_roundtrip"] },
    Gate { id: "V2", property: "bilinear exactness", reference: "sampling an affine field z = ax+by+c returns it exactly", tests: &["bilinear_reproduces_planes_exactly"] },
    Gate { id: "V3", property: "derived layers well-formed", reference: "cover, concealment in [0,1]; mobility >= 1; no NaN", tests: &["derived_layers_well_formed"] },
    Gate { id: "V4", property: "generation determinism", reference: "same seed -> bit-identical raster; different seed differs", tests: &["procedural_terrain_is_deterministic", "procedural_type_painting_fractions"] },
    Gate { id: "V5", property: "flat plane visibility", reference: "two actors with h>0 on flat open ground: clear, tau = 1", tests: &["v5_flat_plane_mutual_visibility"] },
    Gate { id: "V6", property: "single wall shadow", reference: "hidden zone and mask_height match the similar-triangles closed form", tests: &["v6_single_wall_closed_form"] },
    Gate { id: "V7", property: "LOS symmetry", reference: "los(a,b) == los(b,a) in clear and tau, on random terrain", tests: &["v7_symmetry"] },
    Gate { id: "V8", property: "LOS monotonicity", reference: "raising either endpoint never loses visibility; tau falls with canopy", tests: &["v8_monotonicity"] },
    Gate { id: "V9", property: "rigid-motion invariance", reference: "invariant under whole-scenario translation and 90-degree rotation", tests: &["v9_rigid_motion_invariance"] },
    Gate { id: "V10", property: "canopy extinction law", reference: "a Trees strip of width w crossed square-on gives tau = exp(-kw) exactly", tests: &["v10_canopy_extinction_law"] },
    Gate { id: "V11", property: "DDA vs fixed-step oracle", reference: "agrees with an independent fixed-step sampler within a step-driven tolerance", tests: &["v11_matches_fixed_step_oracle"] },
    Gate { id: "V12", property: "flat viewshed is a disc", reference: "on a flat plane the viewshed is exactly the in-range cell set", tests: &["v12_flat_viewshed_is_range_disc"] },
    Gate { id: "V13", property: "ridge shadow", reference: "per-column shadow matches the V6 wall closed form", tests: &["v13_wall_shadow_strip_closed_form"] },
    Gate { id: "V14", property: "detection-time distribution", reference: "MC mean detection time = 1/lambda within CI", tests: &["v14_v15_exponential_law_monte_carlo"] },
    Gate { id: "V15", property: "detection closed form", reference: "MC frequency by time t within binomial CI of 1 - e^(-lambda t)", tests: &["v14_v15_exponential_law_monte_carlo"] },
    Gate { id: "V16", property: "rate structure", reference: "lambda monotone in range/concealment, linear in signature, 0 when gated", tests: &["v16_rate_structure"] },
    Gate { id: "V17", property: "tick-size invariance", reference: "compounded per-tick survival equals e^(-lambda t) for any dt", tests: &["v17_tick_size_invariance"] },
    Gate { id: "V18", property: "sensing determinism", reference: "same (scenario, seed) -> identical event log; different seed differs", tests: &["v18_determinism"] },
    Gate { id: "V19", property: "direct-fire hit probability", reference: "MC impacts inside the WxH rectangle within CI of the erf product", tests: &["v19_direct_hit_probability_monte_carlo"] },
    Gate { id: "V20", property: "hit-probability monotonicity", reference: "falls with range and cover, rises with target size; 0 when blocked", tests: &["v20_direct_hit_monotonicity"] },
    Gate { id: "V21", property: "indirect CEP", reference: "empirical median miss distance = cep_m within CI (Rayleigh)", tests: &["v21_indirect_cep"] },
    Gate { id: "V22", property: "area-damage closed form", reference: "MC mean Carleton damage = R^2/(s^2+R^2) exp(-d^2/2(s^2+R^2))", tests: &["v22_area_damage_closed_form"] },
    Gate { id: "V23", property: "damage monotonicity", reference: "falls with offset and cover, rises with lethal radius", tests: &["v23_area_damage_monotonicity"] },
    Gate { id: "V24", property: "fires determinism", reference: "same (scenario, seed, mission) -> identical rounds and strengths", tests: &["v24_fires_attrit_and_are_deterministic"] },
    Gate { id: "V25", property: "zero-risk = shortest path", reference: "closed-form 8-connected distance (max-min) + sqrt(2)*min", tests: &["v25_zero_risk_is_shortest_path"] },
    Gate { id: "V26", property: "risk avoidance monotone", reference: "raising risk_weight never increases exposure along the optimum", tests: &["v26_risk_avoidance_monotone"] },
    Gate { id: "V27", property: "path optimality", reference: "Dijkstra cost matches an independent Bellman-Ford reference", tests: &["v27_matches_bellman_ford"] },
    Gate { id: "V28", property: "suppression stationary distribution", reference: "birth-death chain occupancy pi_k proportional to (beta/mu)^k", tests: &["v28_stationary_distribution"] },
    Gate { id: "V29", property: "recovery time", reference: "mean time Pinned->Free = 2/recover_per_s (two exponential steps)", tests: &["v29_recovery_time"] },
    Gate { id: "V30", property: "Lanchester square law", reference: "aimed-fire duel conserves A^2 - B^2 in the mean", tests: &["v30_lanchester_square_law"] },
    Gate { id: "V31", property: "suppression gates fire", reference: "Pinned emits nothing; Suppressed output = factor x Free output", tests: &["v31_suppression_gates_fire"] },
    Gate { id: "V32", property: "matching pennies", reference: "fictitious play value -> 0, both strategies -> (1/2, 1/2)", tests: &["v32_matching_pennies"] },
    Gate { id: "V33", property: "rock-paper-scissors", reference: "value -> 0, both strategies -> uniform", tests: &["v33_rock_paper_scissors"] },
    Gate { id: "V34", property: "saddle point", reference: "a game with a pure equilibrium converges to that value", tests: &["v34_saddle_point"] },
    Gate { id: "V35", property: "strict dominance", reference: "a strictly dominated strategy converges to ~0 weight", tests: &["v35_strict_dominance"] },
    Gate { id: "V36", property: "skew-symmetric fairness", reference: "A = -A^T implies value 0; the value bracket closes", tests: &["v36_skew_symmetric"] },
    Gate { id: "V37", property: "route following", reference: "a unit on a straight route is at speed*t after t seconds", tests: &["v37_route_following"] },
    Gate { id: "V38", property: "pinned unit halts", reference: "a Pinned unit does not advance along its route", tests: &["v38_pinned_unit_halts"] },
    Gate { id: "V39", property: "interdiction sanity", reference: "an unwatched route is safe, so Red weights it and the value falls", tests: &["v39_interdiction_safe_route"] },
    Gate { id: "V40", property: "EW modifier", reference: "no jammers => factor exactly 1 (EW-off is the identity); jamming cuts detection monotonically", tests: &["v40_no_jammers_is_identity", "v40_ew_degrades_and_off_is_identity"] },
    Gate { id: "V41", property: "Tiger problem", reference: "exact Bayes posteriors: 0.85 after one observation, 0.9698 after two", tests: &["v41_tiger_problem"] },
    Gate { id: "V42", property: "belief well-formed", reference: "stays a normalised distribution; a peaked likelihood lowers entropy", tests: &["v42_belief_is_proper_and_concentrates"] },
    Gate { id: "V43", property: "negative information", reference: "repeated non-detection shifts belief into dead ground; motion raises entropy", tests: &["v43_negative_information_and_diffusion"] },
    Gate { id: "V44", property: "altitude and masking", reference: "an AMSL drone below a crest is masked where the same drone at AGL is not", tests: &["v44_altitude_and_masking"] },
    Gate { id: "V45", property: "slant range", reference: "sqrt(horizontal^2 + dz^2) exactly; reduces to horizontal when dz = 0", tests: &["v45_slant_range"] },
    Gate { id: "V46", property: "orbit kinematics", reference: "radius holds to epsilon; a lap closes in 2*pi*R/v", tests: &["v46_orbit_kinematics"] },
    Gate { id: "V47", property: "transit and turn rate", reference: "straight leg = speed*t; a turn's chord = 2R sin(phi/2) at R = v/omega", tests: &["v47_transit_and_turn_rate"] },
    Gate { id: "V48", property: "gun time-to-kill", reference: "TTK ~ Exp(lambda): mean 1/lambda, P(kill by t) = 1 - e^(-lambda t)", tests: &["v48_gun_time_to_kill_is_exponential"] },
    Gate { id: "V49", property: "missile time-to-kill", reference: "shots ~ Geometric(p); E[TTK] = t_f/p + (1/p - 1) t_r", tests: &["v49_missile_time_to_kill_is_geometric"] },
    Gate { id: "V50", property: "cue latency and leakage", reference: "leakage = exp(-lambda W_eff); critical latency L* = W + D - R", tests: &["v50_cue_latency_and_leakage"] },
    Gate { id: "V51", property: "envelope and magazine gating", reference: "exactly zero engagements outside band/LOS/cue/magazine; channels capped", tests: &["v51_envelope_and_magazine_gating"] },
    Gate { id: "V52", property: "air-off identity and determinism", reference: "empty air phases draw no randomness (log bit-identical); same seed reproduces", tests: &["v52_air_off_is_a_zero_draw_identity", "v52_air_determinism"] },
    Gate { id: "V53", property: "terrain recipes and presets", reference: "recipe+seed reproduces bit-identically; each layer meets its own invariant (woodland fraction, ridge crest lift); layer order is significant; presets differ as their names claim", tests: &["v53_recipes_are_deterministic_and_layers_do_what_they_say", "v53_presets_expand_to_the_maps_they_name"] },
    Gate { id: "V54", property: "asset removal preserves history", reference: "removal tombstones rather than shifting: every index already in an event log still resolves to the same asset", tests: &["v54_removal_tombstones_keep_logged_indices_valid"] },
    Gate { id: "V55", property: "track lifecycle and EW", reference: "a track lapses track_hold_s after its last observation and is cleared; continuous observation refreshes it; jamming drives the effective glimpse rate below the maintenance threshold and so breaks a track, which permanent detection made impossible", tests: &["v55_tracks_decay_and_ew_can_break_them"] },
    Gate { id: "V56", property: "fire allocation", reference: "Hungarian matches an exhaustive optimum for n,m <= 6 and is never below greedy; no slot is reused and no forbidden pairing chosen; a coordinated side spreads fire across targets where the independent rule doubles up; no shooter is committed to two targets in one epoch; allocation draws no randomness", tests: &["v56_allocation_is_optimal_and_feasible", "v56_allocation_spreads_fire_across_targets", "v56_no_shooter_engages_two_targets_in_one_epoch", "v56_allocation_is_deterministic"] },
    Gate { id: "V57", property: "belief-driven sensor tasking", reference: "against an enemy hidden outside its initial arc, a belief-tasked sensor detects where a fixed stare never does, with a shorter mean time-to-detect; belief stays a normalised non-negative distribution with finite entropy across many updates (extends V42); tasking draws no randomness, so facings reproduce", tests: &["v57_tasking_beats_a_fixed_stare", "v57_belief_stays_a_proper_distribution", "v57_tasking_is_deterministic"] },
    Gate { id: "V58", property: "decision-layer identity", reference: "the Phase 10 phases draw zero randomness: a scenario with no allocation choice and no taskable sensor reproduces the pre-Phase-10 event log bit-identically, and driving the decision phases repeatedly between ticks changes nothing", tests: &["v58_decision_layer_is_a_zero_draw_identity", "v58_single_shooter_matches_the_old_rule"] },
    Gate { id: "V59", property: "C2-coordinated air defence", reference: "with one drone nearest to every battery, nearest-first sends them all at it while a C2 post makes them cover one drone each; a scenario with no post is unchanged from the pre-C2 engine; a dead post coordinates nothing, costing no battery, magazine or envelope — only the coordination; and a post coordinates its OWN side only, so with both sides coordinated each battery still follows its own doctrine and makes the same choice it would make with the enemy's post removed", tests: &["v59_c2_makes_air_defence_split_the_raid", "v59_without_a_post_nothing_changes", "v59_killing_the_post_decoheres_the_defence", "v59_each_side_coordinates_only_its_own_batteries"] },
    Gate { id: "V60", property: "SEAD: air defence is attritable", reference: "a strike drone assigned a named C2 post destroys it in-simulation and the defence decoheres with no battery lost; a destroyed battery's organic radar stops emitting (sensor_active false); a target id matching nothing yields no aim point, so the new asset lists are additive rather than a replacement", tests: &["v60_sead_kills_a_c2_post_and_decoheres_the_defence", "v60_killing_a_battery_takes_its_radar_with_it", "v60_air_defence_assets_are_additive_not_a_replacement"] },
    Gate { id: "V61", property: "carried-sensor coverage informs belief", reference: "a recce drone that flies over ground and finds nothing drains its side's belief out of that ground, where before carried sensors were excluded from the POMDP layer entirely; belief stays normalised; an emplaced-only scenario is unchanged, because only carried sensors are cache-quantised; the cleared ground moves with the drone, so the raster really is refreshed", tests: &["v61_a_recce_drone_informs_belief", "v61_emplaced_sensors_are_unchanged", "v61_a_moving_sensor_keeps_refreshing_its_coverage"] },
    Gate { id: "V62", property: "the C2 link degrades, not only dies", reference: "an enemy jammer on the post scales its coordination radius by the EW factor, so the flanking batteries drop out of the net and the defence decoheres with no battery, post, magazine or envelope touched — the soft twin of killing the post; a *friendly* jammer does not cut its own side's net; a zero-power jammer runs the whole arithmetic and changes nothing (§7.4); link_latency_s delays joining, and a battery not yet in the net falls back to nearest-first, so a late link cannot undo engagements already committed", tests: &["v62_jamming_the_link_decoheres_the_defence", "v62_a_friendly_jammer_does_not_cut_its_own_net", "v62_a_powerless_jammer_is_an_exact_identity", "v62_joining_the_net_costs_time"] },
    Gate { id: "V63", property: "ground fires can be made to need C2", reference: "with [sim] fires_need_c2 on, two guns under a live post engage two targets while the same guns without one both take the nearest — the pre-Phase-10 rule; with the dial off (the default) a C2 post does not touch ground fires at all, so the fire log is bit-identical (§7.4); the net is per shooter, so a post covering two of three guns leaves the third choosing for itself; and jamming scales the post's radius, so a link pulled to 20 m drops a gun 40 m away out of the net while one pulled to 1000 m does not", tests: &["v63_a_post_is_what_lets_ground_fires_coordinate", "v63_the_dial_off_is_an_exact_identity", "v63_the_net_is_per_shooter_not_per_side", "v63_jamming_the_post_breaks_ground_coordination"] },
    Gate { id: "V64", property: "anti-radiation homing", reference: "the same missile against the same battery lands with cep_m when its radar is transmitting and silent_cep_m when it is not, the mean miss scaling as the ratio of the two CEPs (E|miss| = sigma*sqrt(pi/2), sigma = CEP/sqrt(2 ln 2)) and doing correspondingly less damage; a weapon without the flag ignores the emitter entirely, and an ARM with no silent_cep_m stated falls back to cep_m, so both are exact identities; only a named, live, self-cueing battery counts as an emitter, so an ARM aimed at bare ground is blind by definition", tests: &["v64_a_silent_radar_degrades_the_missile", "v64_going_silent_is_the_counter_and_it_costs_the_radar", "v64_an_ordinary_munition_ignores_the_emitter", "v64_only_a_transmitting_battery_counts_as_an_emitter"] },
    Gate { id: "V65", property: "ground counter-battery", reference: "a howitzer in range kills an emitting SAM and the fire log names what it hit, which the unit-only target list could not express; a battery that has neither transmitted nor fired is not located, so indirect fire has nothing to aim at — the same counter V64 poses, now costing the defender artillery cover as well as missile accuracy; direct fire needs line of sight and range but no track, so a silent battery in plain view is still a target; a post is located while it is coordinating and stops being so when it has nothing left to coordinate; and a scenario with no enemy emplacements produces exactly the target list it always did (§7.4)", tests: &["v65_artillery_can_kill_an_emitting_battery", "v65_a_silent_battery_cannot_be_found_by_indirect_fire", "v65_direct_fire_needs_no_track", "v65_a_coordinating_post_is_locatable_and_killing_it_decoheres", "v65_a_scenario_without_emplacements_is_unchanged"] },
    Gate { id: "V66", property: "the kill chain: directed targeting", reference: "a gun with a 46% shot at a near high-value tank and a 3% shot at a far SAM takes the tank unprompted and the SAM when told priority = [air_defence] — strict doctrine is followed, not weighed; the same priority in weighted mode does not overturn the fifteen-fold better shot, which is the difference the two modes exist to express; a directly ordered engagement bypasses the assignment entirely and lapses if its target dies; a side with no doctrine is an exact identity (§7.4); a priority naming nothing on the field is a load error listing what would have worked, and ids, roles and classes are all accepted; air defence follows the same doctrine, taking a further strike drone over a nearer recce one; line of sight and range BLOCK a pairing rather than lowering its score, so a masked priority target does not hold a shooter hostage — both doctrine and an explicit order fall through to what can actually be engaged; and a shooter holds its target until that target is dead or unengageable, with a held lock still counting against that target's discount so two guns with two live targets hold one each", tests: &["v66_strict_doctrine_overrides_a_better_shot", "v66_weighted_doctrine_only_biases", "v66_an_order_pins_a_pairing", "v66_no_doctrine_is_an_exact_identity", "v66_a_priority_naming_nothing_is_a_load_error", "v66_air_defence_follows_the_same_doctrine", "v66_an_unreachable_priority_falls_through_to_the_next_tier", "v66_an_unreachable_order_falls_back_to_the_assignment", "v66_a_lock_is_held_until_the_target_is_finished", "v66_a_lock_is_lost_when_the_target_becomes_unengageable", "v66_a_lock_shifts_the_discount_so_fire_still_spreads"] },
    Gate { id: "V67", property: "the input contract", reference: "a dial the model cannot run on is refused at load, naming it: dt_s or epoch_s at zero or negative (both of which fail to *terminate* — a zero epoch makes time/epoch infinite, and the cast to u64 saturates rather than wrapping, so the epoch loop is handed u64::MAX boundaries), probabilities outside [0,1], negative durations and radii, belief_cells = 0, and any stat-block dial that reaches a divisor (a sensor's range_half_m, an indirect weapon's lethal_radius_m) where a zero yields NaN and NaN loses every comparison it is in; legitimate zeros (a stationary drone, a direct weapon's unused lethal radius, a probability of exactly 0 or 1) still load, and every shipped scenario and library satisfies the contract", tests: &["v67_a_dial_that_would_not_terminate_is_refused_at_load", "v67_a_dial_outside_its_domain_is_refused_at_load", "v67_a_stat_block_that_would_evaluate_to_nan_is_refused", "v67_every_shipped_scenario_and_library_passes_its_own_contract"] },
    Gate { id: "V68", property: "the overkill discount replaces the overkill cap", reference: "with three guns and one target all three engage, where the old hard cap `max_shooters_per_target` assigned nothing to the surplus and they fired nothing at all; with a target each they still take one each, so the geometric discount (1 - qbar)^k delivers the spread the cap was credited with. The cap was removed because it truncated the discount rather than reinforcing it: a shooter with nothing else to engage did nothing, which made a side SPLIT by fires_need_c2 out-fight a coordinated one on fires_c2 (the cap applied once per fire-control problem, so a split side got two)", tests: &["v68_no_gun_idles_when_there_is_only_one_target", "v68_fire_still_spreads_when_there_is_a_target_for_everyone"] },
];
